modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Mozilla Public License 2.0"

[[mods]]
modId = "cobblemonenergy"
version = "${version}"
displayName = "CobblemonEnergy"
authors = "ProgramerGamer"
description = '''

'''
#logoFile = ""

[[dependencies.cobblemonenergy]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonenergy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonenergy]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5.2,)"
ordering = "NONE"
side = "BOTH"
